---
language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  # - jruby-18mode
  # - jruby-19mode
  - ree
env:
  - RAILS_VERSION=""
  - RAILS_VERSION="~>3.2.0"
  - RAILS_VERSION="~>3.1.0"
  - RAILS_VERSION="~>3.0.0"
notifications:
  email:
    - sutto@sutto.net