---
language: ruby
rvm:
  - 1.9.3
env:
  - RAILS_VERSION=""
  - RAILS_VERSION="~>4.0.0"
  - RAILS_VERSION="~>3.2.0"
  - RAILS_VERSION="~>3.1.0"
  - RAILS_VERSION="~>3.0.0"
services: mongodb
notifications:
  email:
    - sutto@sutto.net